# Generated by Django 6.0.3 on 2026-04-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Upload an image related to the issue', null=True, upload_to='issue_images/'),
        ),
    ]
