# Generated by Django 6.0.3 on 2026-04-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issue_images/'),
        ),
    ]
